import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  
  // fetching all posts
  const data = api.posts.getAll.useQuery();

  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && (<>
            <h1> Sign in </h1>
              <SignInButton />
          </>)}
          {!!user.isSignedIn && (<>
            <h1> Sign out </h1>
            <SignOutButton />
          </>)}
        </div>
        <div>
          <h1 className="text-4xl font-bold text-white">Posts</h1>
          <ul>
            {data.data?.map((post) => (
              <li key={post.id}>
                  <a className="text-white">{post.content}</a>

              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
